"""
Generate the FAU gpt-oss-120b teacher smoke template.

A single "setting A"-style config (planning budget=5, running budget=5, student writes
the plan, teacher guides) but with the teacher served by the NHR@FAU gateway
(`fau/gpt-oss-120b`) instead of OpenRouter. Used to validate the new `fau/` provider
end-to-end on a small number of samples.

``build_fau_smoke_template`` is imported by scripts/run_fau_smoke_parallel.py, which
derives per-GPU single-sample variants from it (one episode per GPU). Running this module
directly writes the base template templates/simulations/fau_smoke_gptoss.yaml.

Usage:
    python scripts/gen_fau_smoke_template.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

OUT_DIR = REPO_ROOT / "templates" / "simulations"
DATASET_DIR = "./data/datasets/hotpot_teacher_guidance_exp30"

TEACHER_MODEL = "fau/gpt-oss-120b"
STUDENT_MODEL = "ollama/qwen3.5:4b"
NUM_SAMPLES = 8


def build_fau_smoke_template(
    *,
    template_id: str = "fau_smoke_gptoss",
    student_model: str = STUDENT_MODEL,
    teacher_model: str = TEACHER_MODEL,
    num_samples: int = NUM_SAMPLES,
    questions_path: str = f"{DATASET_DIR}/hotpot_distractor_validation_questions.jsonl",
    corpus_path: str = f"{DATASET_DIR}/hotpot_distractor_validation_corpus.jsonl",
    output_dir: str = "./data/simulation_output/fau_smoke/fau_smoke_gptoss",
) -> dict:
    mode_config = {
        "budget": 5,
        "student_model": student_model,
        "teacher_model": teacher_model,
        "corpus_path": corpus_path,
        "retrieval_backend": "hotpot_local",
        "skip_teacher": False,
        # gpt-oss-120b is a reasoning model: give the teacher a generous completion
        # budget so its chain-of-thought doesn't truncate the JSON verdict.
        "teacher_max_tokens": 2500,
        "teacher_max_tokens_retry": 4000,
        "guidance": {
            "level": 3,
            "name": "diagnostic_feedback",
            "score_mode": "continuous",
            "max_feedback_words": 60,
            "expose_next_action_hint": False,
            "expose_tool_hint": False,
            "expose_query_hint": False,
            "expose_doc_title_hint": False,
            "expose_gold_answer_hint": False,
            "leak_policy": "strict",
        },
        "plan_review": {
            "enabled": True,
            "planner": "student",
            "planning_steps": 1,
            "formal_plan": False,
            "review_guidance_level": 3,
            "max_initial_plan_steps": 6,
            "max_revised_plan_steps": 6,
            "consume_budget": False,
            "include_revised_plan_in_student_context": True,
            "allow_teacher_to_suggest_tools": True,
            "allow_teacher_to_suggest_queries": False,
            "allow_teacher_to_reveal_gold_titles": False,
            "allow_teacher_to_reveal_gold_answer": False,
        },
    }
    return {
        "id": template_id,
        "name": f"FAU gpt-oss-120b teacher smoke ({student_model} student)",
        "mode": "standard",
        "teacher_models": [
            {"name": "student", "model_id": student_model, "role": "teacher", "temperature": 0.2}
        ],
        "consultant_models": [],
        "workflows": ["hotpot_teacher_guided_b5_plan_review"],
        "datasets": [
            {
                "name": "hotpot_questions",
                "path": questions_path,
                "num_samples": num_samples,
                "sample_strategy": "sequential",
            }
        ],
        "max_iterations": 1,
        "similarity_metric": "token_overlap",
        "similarity_threshold": 0.0,
        "verification": {"enabled": False},
        "mode_config": mode_config,
        "output_dir": output_dir,
    }


def generate(out_dir: Path = OUT_DIR) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    template = build_fau_smoke_template()
    path = out_dir / f"{template['id']}.yaml"
    header = (
        "# Auto-generated by scripts/gen_fau_smoke_template.py -- do not hand-edit.\n"
        "# Teacher = fau/gpt-oss-120b (NHR@FAU gateway); student = local Ollama.\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(template, f, sort_keys=False, default_flow_style=False, width=100)
    return path


if __name__ == "__main__":
    print(f"Wrote template -> {generate()}")
